// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#ifndef _MENU_PRACTICE_UI_H
#define _MENU_PRACTICE_UI_H

#ifdef __cplusplus
extern "C" {
#endif
// C:\Users\VHT-Student\Itachi\projects\esp-box\esp-box\examples\lv_demos\managed_components\lvgl__lvgl\lvgl.h
#include "../../managed_components/lvgl__lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Header1;
extern lv_obj_t * ui_simulateDropdown1;
void ui_event_btnChangeScreen1(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen1;
void ui_event_btnChangeScreen2(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen2;
void ui_event_btnChangeScreen3(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Header2;
extern lv_obj_t * ui_simulateDropdown2;
void ui_event_btnChangeScreen4(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen4;
void ui_event_btnChangeScreen5(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen5;
void ui_event_btnChangeScreen6(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen6;
extern lv_obj_t * ui_SwitchList;
extern lv_obj_t * ui_LabelSw1;
extern lv_obj_t * ui_LabelSw2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Header3;
extern lv_obj_t * ui_simulateDropdown3;
void ui_event_btnChangeScreen7(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen7;
void ui_event_btnChangeScreen8(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen8;
void ui_event_btnChangeScreen9(lv_event_t * e);
extern lv_obj_t * ui_btnChangeScreen9;
// SCREEN: ui_Item
void ui_Item_screen_init(void);
extern lv_obj_t * ui_Item;
extern lv_obj_t * ui_hidddenWipeGesture;
void ui_event_hideWipe4(lv_event_t * e);
extern lv_obj_t * ui_hideWipe4;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_657858778);    // assets\down-arrow-56.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
