// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#ifndef _MENU_PRACTICE_UI_H
#define _MENU_PRACTICE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Header1;
extern lv_obj_t * ui_btnDropdown;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Header2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Header3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1382514998);    // assets\93-936844_down-arrow-png-image-background-down-arrow-icon.png
LV_IMG_DECLARE(ui_img_657858778);    // assets\down-arrow-56.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
