// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#include "../ui.h"

// COMPONENT hideWipe

lv_obj_t * ui_hideWipe_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_hideWipe;
    cui_hideWipe = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_hideWipe, lv_pct(100));
    lv_obj_set_height(cui_hideWipe, lv_pct(90));
    lv_obj_set_align(cui_hideWipe, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_hideWipe, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_hideWipe, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HIDEWIPE_NUM);
    children[UI_COMP_HIDEWIPE_HIDEWIPE] = cui_hideWipe;
    lv_obj_add_event_cb(cui_hideWipe, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_hideWipe, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_hideWipe_create_hook(cui_hideWipe);
    return cui_hideWipe;
}

