// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#ifndef _MENU_PRACTICE_UI_COMP_HOOK_H
#define _MENU_PRACTICE_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Header_create_hook(lv_obj_t * comp);
void ui_comp_hideWipe_create_hook(lv_obj_t * comp);
void ui_comp_LabelSw_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
