// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#ifndef _UI_COMP_LABELSW_H
#define _UI_COMP_LABELSW_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LabelSw
#define UI_COMP_LABELSW_LABELSW 0
#define UI_COMP_LABELSW_SWCONTROL 1
#define UI_COMP_LABELSW_SWLABEL 2
#define _UI_COMP_LABELSW_NUM 3
lv_obj_t * ui_LabelSw_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
