// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#include "../ui.h"

// COMPONENT LabelSw

lv_obj_t * ui_LabelSw_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_LabelSw;
    cui_LabelSw = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_LabelSw, 230);
    lv_obj_set_height(cui_LabelSw, 50);
    lv_obj_set_x(cui_LabelSw, -22);
    lv_obj_set_y(cui_LabelSw, 50);
    lv_obj_set_align(cui_LabelSw, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_LabelSw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_swControl;
    cui_swControl = lv_switch_create(cui_LabelSw);
    lv_obj_set_width(cui_swControl, 50);
    lv_obj_set_height(cui_swControl, 20);
    lv_obj_set_x(cui_swControl, 83);
    lv_obj_set_y(cui_swControl, 0);
    lv_obj_set_align(cui_swControl, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_swControl, LV_STATE_FOCUSED);       /// States

    lv_obj_t * cui_swLabel;
    cui_swLabel = lv_textarea_create(cui_LabelSw);
    lv_obj_set_width(cui_swLabel, 159);
    lv_obj_set_height(cui_swLabel, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(cui_swLabel, -28);
    lv_obj_set_y(cui_swLabel, 0);
    lv_obj_set_align(cui_swLabel, LV_ALIGN_CENTER);
    lv_textarea_set_text(cui_swLabel, "Control ");
    lv_textarea_set_placeholder_text(cui_swLabel, "Placeholder...");
    lv_textarea_set_one_line(cui_swLabel, true);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELSW_NUM);
    children[UI_COMP_LABELSW_LABELSW] = cui_LabelSw;
    children[UI_COMP_LABELSW_SWCONTROL] = cui_swControl;
    children[UI_COMP_LABELSW_SWLABEL] = cui_swLabel;
    lv_obj_add_event_cb(cui_LabelSw, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_LabelSw, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_LabelSw_create_hook(cui_LabelSw);
    return cui_LabelSw;
}

