// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#include "../ui.h"

void ui_Item_screen_init(void)
{
    ui_Item = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Item, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Item, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Item);

    ui_hidddenWipeGesture = ui_hideWipe_create(ui_Item);
    lv_obj_set_x(ui_hidddenWipeGesture, 0);
    lv_obj_set_y(ui_hidddenWipeGesture, 0);

    ui_hideWipe4 = lv_obj_create(ui_Item);
    lv_obj_set_width(ui_hideWipe4, lv_pct(100));
    lv_obj_set_height(ui_hideWipe4, lv_pct(53));
    lv_obj_set_align(ui_hideWipe4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_hideWipe4, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_hideWipe4, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_FLOATING |
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_FLEX_IN_NEW_TRACK | LV_OBJ_FLAG_EVENT_BUBBLE);    /// Flags
    lv_obj_clear_flag(ui_hideWipe4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_hideWipe4, ui_event_hideWipe4, LV_EVENT_ALL, NULL);

}
