// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#include "../ui.h"


void ui_btnDropdown_event_cb(lv_event_t* e);

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header1 = ui_Header_create(ui_Screen1);
    lv_obj_set_x(ui_Header1, 0);
    lv_obj_set_y(ui_Header1, 0);

    ui_btnDropdown = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnDropdown, 80);
    lv_obj_set_height(ui_btnDropdown, 30);
    lv_obj_set_x(ui_btnDropdown, 108);
    lv_obj_set_y(ui_btnDropdown, -56);
    lv_obj_set_align(ui_btnDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnDropdown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnDropdown, lv_color_hex(0x858181), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // Custom part
    lv_obj_add_event_cb(ui_btnDropdown, ui_btnDropdown_event_cb, LV_EVENT_ALL, NULL);
}

void event_handler_dropdown_btn_opts_settings(lv_event_t* e);
void event_handler_dropdown_btn_opts_about(lv_event_t* e);

void ui_btnDropdown_event_cb(lv_event_t* e)
{
    lv_event_code_t code = lv_event_get_code(e);

    lv_obj_t* btn;

    if (code == LV_EVENT_CLICKED) {
        lv_obj_t *dropdwn_list= lv_list_create(ui_Screen1);
        lv_obj_t* btn;

        // Need port
        btn = lv_list_add_btn(dropdwn_list, LV_SYMBOL_SETTINGS, "Settings");
            (btn, event_handler_dropdown_btn_opts_settings, LV_EVENT_CLICKED, NULL);
        btn = lv_list_add_btn(dropdwn_list, LV_SYMBOL_FILE, "About");
        lv_obj_add_event_cb(btn, event_handler_dropdown_btn_opts_about, LV_EVENT_CLICKED,NULL);
        lv_obj_set_height(dropdwn_list, LV_SIZE_CONTENT);
        lv_obj_align(dropdwn_list, LV_ALIGN_TOP_RIGHT, 0, 0);
    }
}
