// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header1 = ui_Header_create(ui_Screen1);
    lv_obj_set_x(ui_Header1, 0);
    lv_obj_set_y(ui_Header1, 0);

    ui_simulateDropdown1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_simulateDropdown1, 131);
    lv_obj_set_height(ui_simulateDropdown1, 165);
    lv_obj_set_x(ui_simulateDropdown1, -84);
    lv_obj_set_y(ui_simulateDropdown1, 20);
    lv_obj_set_align(ui_simulateDropdown1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_simulateDropdown1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_simulateDropdown1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_simulateDropdown1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_simulateDropdown1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_btnChangeScreen1 = lv_btn_create(ui_simulateDropdown1);
    lv_obj_set_width(ui_btnChangeScreen1, 100);
    lv_obj_set_height(ui_btnChangeScreen1, 35);
    lv_obj_set_x(ui_btnChangeScreen1, 0);
    lv_obj_set_y(ui_btnChangeScreen1, -53);
    lv_obj_set_align(ui_btnChangeScreen1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnChangeScreen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnChangeScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnChangeScreen2 = lv_btn_create(ui_simulateDropdown1);
    lv_obj_set_width(ui_btnChangeScreen2, 100);
    lv_obj_set_height(ui_btnChangeScreen2, 35);
    lv_obj_set_x(ui_btnChangeScreen2, 0);
    lv_obj_set_y(ui_btnChangeScreen2, -53);
    lv_obj_set_align(ui_btnChangeScreen2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnChangeScreen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnChangeScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnChangeScreen3 = lv_btn_create(ui_simulateDropdown1);
    lv_obj_set_width(ui_btnChangeScreen3, 100);
    lv_obj_set_height(ui_btnChangeScreen3, 35);
    lv_obj_set_x(ui_btnChangeScreen3, 0);
    lv_obj_set_y(ui_btnChangeScreen3, -53);
    lv_obj_set_align(ui_btnChangeScreen3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnChangeScreen3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnChangeScreen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnChangeScreen1, ui_event_btnChangeScreen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnChangeScreen2, ui_event_btnChangeScreen2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnChangeScreen3, ui_event_btnChangeScreen3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
