// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: menu_practice

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header2 = ui_Header_create(ui_Screen2);
    lv_obj_set_x(ui_Header2, 0);
    lv_obj_set_y(ui_Header2, 0);

    lv_label_set_text(ui_comp_get_child(ui_Header2, UI_COMP_HEADER_SCREENNAME), "Screen 2");

}
